TRUCK_MAINTENANCE_ITEMS = [
    { 'id': 'cinto_seguranca', 'label': '1 - Cinto de segurança perfeito e funcionando?' },
    { 'id': 'pneus_estado', 'label': '2 - Pneus em bom estado? Descreva situação!' },
    { 'id': 'rodas_estado', 'label': '3 - Rodas em bom estado?' },
    { 'id': 'freio_perfeito', 'label': '4 - Freio funcionando perfeitamente? Lonas' },
    { 'id': 'freio_estacionamento', 'label': '5 - Freio de Estacionamento ok?' },
    { 'id': 'direcao_estado', 'label': '6 - Direção em bom estado?' },
    { 'id': 'limpador_parabrisa', 'label': '7 - Limpador de Pára-Brisa funcionando bem? Com água?' },
    { 'id': 'instrumentos_painel', 'label': '8 - Instrumentos do Painel?' },
    { 'id': 'retrovisor_estado', 'label': '9 - Retrovisor em perfeito estado?' },
    { 'id': 'buzina_funcionando', 'label': '10 - Buzina funcionando?' },
    { 'id': 'farol_funcionando', 'label': '11 - Farol funcionando bem? Principais' },
    { 'id': 'setas_funcionando', 'label': '12 - Setas funcionando?' },
    { 'id': 'alerta_funcionando', 'label': '13 - Alerta funcionando?' },
    { 'id': 'luz_alarme_re', 'label': '14 - Luz de Ré e Alarme de Ré funcionando?' },
    { 'id': 'luz_freio', 'label': '15 - Luz de Freio funcionando?' },
    { 'id': 'extintor_vencimento', 'label': '16 - Extintor ok? Anotar o Vencimento em Observação!' },
    { 'id': 'oleo_hidraulico', 'label': '17 - Óleo Hidráulico, nível correto?' },
    { 'id': 'oleo_freio', 'label': '18 - Óleo de Freio, nível correto?' },
    { 'id': 'oleo_motor', 'label': '19 - Óleo de Motor na validade e nível correto?' },
    { 'id': 'correias_estado', 'label': '20 - Correias em bom estado?' },
    { 'id': 'agua_radiador', 'label': '21 - Água do radiador?' },
    { 'id': 'bateria_estado', 'label': '22 - Bateria ok?' },
    { 'id': 'escapamento_estado', 'label': '23 - Escapamento ok?' },
    { 'id': 'tampa_combustivel', 'label': '24 - Tampa de combustível, existe e está ok?' },
    { 'id': 'macaco_hidraulico', 'label': '25 - Tem macaco hidráulico?' },
    { 'id': 'bancos_limpeza', 'label': '26 - Bancos em bom estado? E limpeza do veículo?' },
    { 'id': 'chave_triangulo', 'label': '27 - Chave de segurança e Triângulo de Sinalização existe?' },
    { 'id': 'tacografo_disco', 'label': '28 - Tacógrafo funcionando? Possui disco?' },
    { 'id': 'carroceria_estado', 'label': '29 - Carroceria em bom estado?' },
]

TRAILER_MAINTENANCE_ITEMS = [
    { 'id': 'perfil_dianteiro', 'label': '1 - Perfil dianteiro' },
    { 'id': 'perfil_traseiro', 'label': '2 - Perfil traseiro' },
    { 'id': 'perfil_lateral_dir', 'label': '3 - Perfil lateral direito?' },
    { 'id': 'perfil_lateral_esq', 'label': '4 - Perfil lateral esquerdo?' },
    { 'id': 'freio_estacionamento', 'label': '5 - Freio de Estacionamento ok?' },
    { 'id': 'alinhamento_eixos', 'label': '6 - Alinhamento dos eixos?' },
    { 'id': 'parachoques', 'label': '7 - Pára-choque ?' },
    { 'id': 'aparabarros', 'label': '8 - Aparabarros?' },
    { 'id': 'paralamas', 'label': '9 - Paralamas?' },
    { 'id': 'pes_carreta', 'label': '10 - Pés da carreta?' },
    { 'id': 'suspensor_1eixo', 'label': '11 - Suspensor 1º eixo?' },
    { 'id': 'suspensor_2eixo', 'label': '12 - Suspensor 2º eixo?' },
    { 'id': 'alerta', 'label': '13 - Alerta?' },
    { 'id': 'setas', 'label': '14 - Setas?' },
    { 'id': 'luz_freio', 'label': '15 - Luz de freio?' },
    { 'id': 'luz_re', 'label': '16 - Luz de ré?' },
    { 'id': 'luz_placa', 'label': '17 - Luz de placa ?' },
    { 'id': 'lentes_laterais', 'label': '18 - Lentes laterais?' },
    { 'id': 'pino_rei', 'label': '19 - Pino Rei?' },
    { 'id': 'sistema_pneumatico', 'label': '20 - Sistema pneumático ?' },
    { 'id': 'engate_eletrico', 'label': '21 - Engate elétrico?' },
    { 'id': 'engates_pneumaticos', 'label': '22 - Engates pneumáticos?' },
    { 'id': 'tampas_lat_dir', 'label': '23 - Tampas Laterais direita?' },
    { 'id': 'tampas_lat_esq', 'label': '24 - Tampas Laterais esquerda?' },
    { 'id': 'tampa_traseira', 'label': '25 - Tampa traseira?' },
    { 'id': 'tampa_dianteira', 'label': '26 - Tampa dianteira?' },
    { 'id': 'pinos_locke', 'label': '27 - Pinos locke?' },
    { 'id': 'faixas_refletivas', 'label': '28 - Faixas refletivas?' },
    { 'id': 'faixa_parachoques', 'label': '29 - Faixa pára-choque?' },
    { 'id': 'suporte_estepe', 'label': '30 - Suporte do estepe?' },
    { 'id': 'suspensao_geral', 'label': '31 - Suspensão em geral?' },
]

PORTARIA_ITEMS = [
    { 'id': 'eletrica_condicoes', 'label': 'Sist. Elétrico' },
    { 'id': 'eletrica_seta', 'label': 'Setas' },
    { 'id': 'eletrica_re', 'label': 'Luz de Ré' },
    { 'id': 'eletrica_freio', 'label': 'Luz de Freio' },
    { 'id': 'eletrica_capas', 'label': 'Capas das Lanternas' },
    { 'id': 'eletrica_placa', 'label': 'Luz de Placa' },
    { 'id': 'mecanica_freios', 'label': 'Freios Regulados' },
    { 'id': 'mecanica_conexoes', 'label': 'Conexões Engate' },
    { 'id': 'mecanica_folga_quinta_roda', 'label': 'Folga 5ª Roda' },
    { 'id': 'mecanica_suspensao', 'label': 'Suspensão' },
    { 'id': 'mecanica_freio_estacionario', 'label': 'Freio Estacionário' },
    { 'id': 'mecanica_travas_conteiner', 'label': 'Travas Contêiner' },
    { 'id': 'mecanica_tampas_equipamento', 'label': 'Tampas Equipamento' },
    { 'id': 'mecanica_tampas_estado', 'label': 'Estado das Tampas' },
    { 'id': 'rodas_pneus_quantidade', 'label': 'Quantidade Pneus' },
    { 'id': 'rodas_pneus_reserva', 'label': 'Pneu Reserva' },
    { 'id': 'rodas_pneus_estado', 'label': 'Estado Geral Pneus' },
    { 'id': 'rodas_pneus_cortes_bolhas', 'label': 'Cortes/Bolhas' },
]

FORKLIFT_ITEMS = [
    { 'id': 'mangueiras', 'label': '1 - Mangueiras estão em bom estado?' },
    { 'id': 'pneus', 'label': '2 - Pneus em bom estado?' },
    { 'id': 'pistao_elevacao', 'label': '3 - Pistão de Elevação ok?' },
    { 'id': 'pistao_inclinacao', 'label': '4 - Pistão de Inclinação ok?' },
    { 'id': 'direcao', 'label': '5 - Direção em bom estado?' },
    { 'id': 'cabo_aco', 'label': '6 - Cabo de Aço em bom estado?' },
    { 'id': 'parte_eletrica', 'label': '7 - Parte Elétrica funcionando?' },
    { 'id': 'corrente_torre', 'label': '8 - Corrente da Torre ok?' },
    { 'id': 'vazamento_oleo', 'label': '9 - Sem vazamento de óleo?' },
    { 'id': 'pintura', 'label': '10 - Pintura em bom estado?' },
]
