# Generated by Django 6.0.3 on 2026-03-27 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('placa_cavalo', models.CharField(max_length=10)),
                ('nome_motorista', models.CharField(max_length=255)),
                ('placa_carreta', models.CharField(max_length=10)),
                ('doc_carreta_entregue', models.BooleanField(default=False)),
                ('tipo_equipamento', models.CharField(choices=[('PRANCHA', 'Carreta Prancha'), ('TAMPA', 'Carreta com Tampa'), ('BUGRE_20', 'Bugre de 20'), ('BITREM', 'Carreta de Bitrem')], max_length=20)),
                ('eletrica_condicoes', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('eletrica_seta', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('eletrica_re', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('eletrica_freio', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('eletrica_capas', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('eletrica_placa', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('mecanica_freios', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('mecanica_conexoes', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('mecanica_folga_quinta_roda', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('mecanica_suspensao', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('mecanica_freio_estacionario', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('mecanica_travas_conteiner', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('mecanica_tampas_equipamento', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('mecanica_tampas_estado', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('rodas_pneus_quantidade', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('rodas_pneus_reserva', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('rodas_pneus_estado', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('rodas_pneus_cortes_bolhas', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('anomalias', models.TextField(blank=True, null=True)),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('visto_responsavel_saida', models.CharField(blank=True, max_length=255, null=True)),
                ('visto_motorista_saida', models.CharField(blank=True, max_length=255, null=True)),
                ('data_hora_devolucao', models.DateTimeField(blank=True, null=True)),
                ('visto_responsavel_devolucao', models.CharField(blank=True, max_length=255, null=True)),
                ('visto_motorista_devolucao', models.CharField(blank=True, max_length=255, null=True)),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PORTEIRO', 'Porteiro'), ('GESTOR', 'Gestor'), ('ADMIN', 'Admin')], default='PORTEIRO', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
