# Generated by Django 6.0.3 on 2026-03-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='placa_carreta',
        ),
        migrations.AddField(
            model_name='checklist',
            name='placa_carreta_01',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Carreta 01'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='placa_carreta_02',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Carreta 02'),
        ),
    ]
