# Generated by Django 6.0.3 on 2026-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_remove_checklist_placa_carreta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='visto_motorista_devolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='visto_motorista_saida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='visto_responsavel_devolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='visto_responsavel_saida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
