# Generated by Django 6.0.3 on 2026-03-27 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_checklist_visto_motorista_devolucao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='data_hora_saida',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='nome_motorista',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='placa_carreta_01',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='placa_carreta_02',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='porteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='tipo_equipamento',
            field=models.CharField(choices=[('PRANCHA', 'Prancha'), ('TAMPA', 'Com Tampa'), ('BUGRE_20', "Bugre 20'"), ('BITREM', 'Bitrem')], default='PRANCHA', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GESTOR', 'Gestor'), ('PORTEIRO', 'Porteiro')], default='PORTEIRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
