# Generated by Django 6.0.3 on 2026-03-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_alertemail_remove_checklist_data_hora_saida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('CAVALO', 'Cavalo Mecânico'), ('CARRETA', 'Carreta')], max_length=20)),
                ('id_frota', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('ano_modelo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='nome_motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='checklists.condutor'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='placa_carreta_01',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'CARRETA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_carreta1', to='checklists.veiculo'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='placa_carreta_02',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'CARRETA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_carreta2', to='checklists.veiculo'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='placa_cavalo',
            field=models.ForeignKey(limit_choices_to={'tipo': 'CAVALO'}, on_delete=django.db.models.deletion.PROTECT, related_name='checklists_cavalo', to='checklists.veiculo'),
        ),
    ]
