# Generated by Django 6.0.3 on 2026-03-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_condutor_veiculo_profile_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GESTOR', 'Gestor'), ('CONTROLADOR', 'Controlador de Acesso'), ('MANUTENCAO', 'Manutenção')], default='CONTROLADOR', max_length=20),
        ),
    ]
