# Generated by Django 6.0.3 on 2026-03-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_maintenancetrailer_maintenancetruck'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertemail',
            name='category',
            field=models.CharField(choices=[('PORTARIA', 'Portaria / Controlador de Acesso'), ('MANUTENCAO', 'Manutenção')], default='PORTARIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertemail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='alertemail',
            unique_together={('email', 'category')},
        ),
    ]
