# Generated by Django 6.0.2 on 2026-04-08 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_alertemail_category_alter_alertemail_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistForklift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipamento', models.CharField(choices=[('MILA', 'MILA'), ('ASA_DELTA', 'ASA DELTA'), ('HYSTER', 'HYSTER DE 7 TON')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('mangueiras', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('pneus', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('pistao_elevacao', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('pistao_inclinacao', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('direcao', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('cabo_aco', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('parte_eletrica', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('corrente_torre', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('vazamento_oleo', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('pintura', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('visto_responsavel', models.TextField(blank=True, null=True)),
                ('visto_operador', models.TextField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forklift_checklists', to='checklists.condutor')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forklift_checklists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
