# Generated by Django 6.0.3 on 2026-04-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_checklistforklift'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='tempo_execucao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistforklift',
            name='tempo_execucao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancetrailer',
            name='tempo_execucao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancetruck',
            name='tempo_execucao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
