# Generated by Django 6.0.3 on 2026-04-08 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0011_alertwhatsapp_maintenanceschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertemail',
            options={'verbose_name': 'Alerta de E-mail', 'verbose_name_plural': 'Alertas de E-mail'},
        ),
        migrations.AlterModelOptions(
            name='alertwhatsapp',
            options={'verbose_name': 'Alerta de WhatsApp', 'verbose_name_plural': 'Alertas de WhatsApp'},
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Checklist de Portaria', 'verbose_name_plural': 'Checklists de Portaria'},
        ),
        migrations.AlterModelOptions(
            name='checklistforklift',
            options={'verbose_name': 'Checklist de Empilhadeira', 'verbose_name_plural': 'Checklists de Empilhadeira'},
        ),
        migrations.AlterModelOptions(
            name='condutor',
            options={'verbose_name': 'Motorista/Condutor', 'verbose_name_plural': 'Motoristas/Condutores'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'verbose_name': 'Agendamento de Manutenção', 'verbose_name_plural': 'Agendamentos de Manutenção'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetrailer',
            options={'verbose_name': 'Manutenção de Carreta', 'verbose_name_plural': 'Manutenções de Carreta'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetruck',
            options={'verbose_name': 'Manutenção de Caminhão', 'verbose_name_plural': 'Manutenções de Caminhão'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.CreateModel(
            name='MaintenanceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='checklists.maintenanceschedule')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Manutenção',
                'verbose_name_plural': 'Históricos de Manutenção',
                'ordering': ['-created_at'],
            },
        ),
    ]
