# Generated by Django 6.0.3 on 2026-04-08 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0012_alter_alertemail_options_alter_alertwhatsapp_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetrailer',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='maintenancetruck',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='checklist',
            name='data_resolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_portaria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistforklift',
            name='data_resolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistforklift',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_forklifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetrailer',
            name='data_resolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancetrailer',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_trailers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetruck',
            name='data_resolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancetruck',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_trucks', to=settings.AUTH_USER_MODEL),
        ),
    ]
