# Generated by Django 6.0.3 on 2026-04-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0013_remove_maintenancetrailer_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetruck',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
