# Generated by Django 6.0.3 on 2026-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0014_maintenancetruck_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertemail',
            name='category',
            field=models.CharField(choices=[('PORTARIA', 'Portaria / Controlador de Acesso'), ('MANUTENCAO', 'Manutenção'), ('AGENDA', 'Agenda de Manutenção')], default='PORTARIA', max_length=20),
        ),
    ]
