# Generated by Django 6.0.3 on 2026-04-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0015_alter_alertemail_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chat_id', models.CharField(help_text='ID numérico do chat ou usuário no Telegram', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta de Telegram',
                'verbose_name_plural': 'Alertas de Telegram',
            },
        ),
        migrations.DeleteModel(
            name='AlertWhatsApp',
        ),
    ]
