# Generated by Django 6.0.3 on 2026-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0016_alerttelegram_delete_alertwhatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='email-ssl.com.br', max_length=255)),
                ('port', models.IntegerField(default=465)),
                ('user', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('use_tls', models.BooleanField(default=False)),
                ('use_ssl', models.BooleanField(default=True)),
                ('default_from', models.EmailField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configurações de E-mail',
            },
        ),
    ]
