# Generated by Django 6.0.3 on 2026-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0018_telegramconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramconfig',
            name='bot_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
