# Generated by Django 6.0.2 on 2026-04-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0020_checklistphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GESTOR', 'Gestor'), ('CONTROLADOR', 'Controlador de Acesso'), ('MANUTENCAO', 'Manutenção'), ('DEPOT', 'Depot (Empilhadeiras)')], default='CONTROLADOR', max_length=20),
        ),
    ]
