# Generated by Django 6.0.2 on 2026-04-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0022_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='tipo_equipamento',
        ),
    ]
