# Generated by Django 6.0.2 on 2026-04-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0023_remove_checklist_tipo_equipamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='ano_fabricacao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ano_modelo',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='id_frota',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='modelo',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(blank=True, choices=[('BUGGY', 'Buggy'), ('BUGGY_20', 'Buggy 20'), ('CARRETA', 'Carreta'), ('BAU_SECO', 'Baú Seco'), ('BAU_REFRI', 'Baú Refrigerado'), ('SIDER', 'Sider'), ('PRANCHA', 'Prancha')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca_modelo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
