# Generated by Django 6.0.3 on 2026-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0025_profile_telegram_chat_id_telegramtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='resend_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='use_api',
            field=models.BooleanField(default=False, verbose_name='Usar API Web (Resend)'),
        ),
    ]
