# Generated by Django 5.2.7 on 2026-05-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0026_emailconfig_resend_api_key_emailconfig_use_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='condutor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
