# Generated by Django 6.0.3 on 2026-07-17 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0027_condutor_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('CAVALO', 'Cavalo Mecânico'), ('CARRETA', 'Carreta'), ('CARRO_COMERCIAL', 'Carro Comercial')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChecklistCarroComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_condutor', models.CharField(max_length=100, verbose_name='Nome do Condutor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('quilometragem', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_combustivel', models.IntegerField(default=0)),
                ('partida_motor', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('pneus', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('lataria', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('lanternas_farois', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('estofamento_painel_teto', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('limpeza', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('step_macaco_triangulo', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('tempo_execucao', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('visto_responsavel', models.TextField(blank=True, null=True)),
                ('visto_motorista', models.TextField(blank=True, null=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_commercial_cars', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(limit_choices_to={'tipo': 'CARRO_COMERCIAL'}, on_delete=django.db.models.deletion.PROTECT, to='checklists.veiculo')),
            ],
            options={
                'verbose_name': 'Checklist de Carro Comercial',
                'verbose_name_plural': 'Checklists de Carro Comercial',
            },
        ),
    ]
