# Generated by Django 5.2.7 on 2026-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0028_alter_veiculo_tipo_checklistcarrocomercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='eixo_erguido_carreta_01',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='eixo_erguido_carreta_02',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='eixo_erguido_cavalo',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='eletrica_sirene_re',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='rodas_pneus_calco',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3),
        ),
    ]
