# Generated by Django 6.0.3 on 2026-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0029_checklist_eixo_erguido_carreta_01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='tipo_checklist',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], default='ENTRADA', max_length=10, verbose_name='Tipo de Checklist'),
        ),
    ]
