# Generated by Django 6.0.3 on 2026-09-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0030_checklist_tipo_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='eletrica_sirene_re_carreta_01',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='checklist',
            name='eletrica_sirene_re_carreta_02',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'N/A')], default='NA', max_length=3),
        ),
    ]
