# Generated by Django 5.2.7 on 2026-10-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0031_checklist_eletrica_sirene_re_carreta_01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistcarrocomercial',
            name='tipo_checklist',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], default='SAIDA', max_length=20),
        ),
    ]
